environments:
  cluster-azure-us-west:
    values:
      - git::https://github.com/rahulwagh/helmchart@helloworld?ref=master&sparse=0

releases:
  - name: helloworld1
    chart: ./helloworld1
    installed: true
